name: Cypress end-to-end tests
run-name: End-to-end tests - running on ${{ github.event.inputs.browser || 'chrome' }}

on: 
  push:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run test in'
        required: true
        default: 'chrome'
        type: choice
        options:
         - chrome
         - chromium
         - firefox
         - edge
         - electron

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          browser: ${{ github.event.inputs.browser }}
          headed: ${{ github.event.inputs.headless }}

      # Upload screenshots of failed tests
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ github.event.inputs.browser || 'chrome' }}
          path: cypress/screenshots
          if-no-files-found: ignore 

      # Upload video
      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ github.event.inputs.browser || 'chrome' }}
          path: cypress/videos
          if-no-files-found: ignore
